version: 0.0.{build}

image: Visual Studio 2019

test: off

build:
  publish_nuget: true

install:
  - cmd: git submodule update --init

build_script:
  - ps: .\build.ps1 -Target Package # -Verbosity Diagnostic -buildVerbosity=Verbose

artifacts:
  - path: YamlDotNet\bin\Release\netstandard2.1
    name: Release-NetStandard-2.1

  - path: YamlDotNet\bin\Release\netstandard1.3
    name: Release-NetStandard-1.3

  - path: YamlDotNet\bin\Release\net45
    name: Release-Net45

  - path: YamlDotNet\bin\Release\net35
    name: Release-Net35

  - path: YamlDotNet\bin\Release\net20
    name: Release-Net20

  - path: YamlDotNet\bin\Release\net40
    name: Release-UnitySubset-v35

  - path: YamlDotNet\bin\*.nupkg

deploy:
  - provider: NuGet
    on:
      APPVEYOR_REPO_TAG: true
    api_key:
      secure: ojJHQQHSQs/rgIRopbuHUQcjWpVgwaXhjYpW2kdkjS6NZta2A3Zzaz9k2yf+XooV
    artifact: /.*\.nupkg/
