version: 1.0.{build}
branches:
  only:
    - master
    - temp-appveyor-integration

os: Windows Server 2012 R2

install:
  - cmd: git submodule update --init
  - ps:  .\prebuild.ps1
  - cmd: nuget restore

platform: Any CPU
configuration: Release

build:
  publish_nuget: true
