version: 0.0.{build}

image: Visual Studio 2017

build:
  publish_nuget: true

install:
  - cmd: git submodule update --init

build_script:
  - ps: .\build.ps1 -Target Package # -Verbosity Diagnostic -buildVerbosity=Verbose

artifacts:
  - path: YamlDotNet\bin\Release-Unsigned\net35
    name: Release-Unsigned

  - path: YamlDotNet\bin\Release-Signed\net35
    name: Release-Signed

  - path: YamlDotNet\bin\Release-Portable-Unsigned
    name: Release-Portable-Unsigned

  - path: YamlDotNet\bin\Release-Portable-Signed
    name: Release-Portable-Signed

  - path: YamlDotNet\bin\Release-DotNetStandard-Unsigned\netstandard1.3
    name: Release-DotNetStandard-Unsigned

  - path: YamlDotNet\bin\Release-DotNetStandard-Signed\netstandard1.3
    name: Release-DotNetStandard-Signed

  - path: YamlDotNet\bin\Release-UnitySubset-v35
    name: Release-UnitySubset-v35

  - path: YamlDotNet\bin\*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: GMc0xUTASI8qTPK1/eN/GFs6PBhPFBin1TT1hE5N8NlkU7VSBx3z4zQinSv/ICmx
    artifact: /.*\.nupkg/

test: off
